language: python

python:
  - 3.8

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=ttg --cov-report term-missing

after_success:
  - pipenv run codecov
